version: '3.8'
services:
  web:
    image: discover-cars:v1
    ports:
      - "3000:3000"
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - web

