version: '3.8'
services:
  web:
    image: discover-cars
    ports:
      - "3000:3000"
  proxy:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8080:80"
    depends_on:
      - web
